class Socket {
  static Request = {
    CONNECTION: "connection",
    DISCONNECT: "disconnect",
    REGISTER_USER: "register-user",
    LOGIN_USER: "login-user",
    UPDATE_PROFILE: "update-profile",
    DELETE_PROFILE: "delete-profile",
    PROGRESS_UPDATE: "request-progress-update",
    GET_SITE_SETTINGS: "get-site-settings",
    UPDATE_SITE_SETTINGS: "update-site-settings",
    CREATE_GAME: "create-game",
    CURRENT_USERS: "get-current-users",
    CURRENT_GAMES: "get-current-games",
    PLAY_MOVE: "play-move",
    LOAD_GAME: "load-game",
    RENAME_GAME: "rename-game",
    CHANGE_ICON: "change-icon",
    RESET_ROUNDS: "reset-rounds",
    DELETE_GAME: "delete-game",
    RECENT_GAMES: "get-recent-games",
    JOIN_CHATS: "get-conversations",
    START_CONVERSATION: "start-conversation",
    JOIN_CHAT: "join-chat",
    SEND_MESSAGE: "send-message",
  };

  static Response = {
    CONNECTION: "user-connected",
    DISCONNECT: "disconnected",
    REGISTER_USER: "user-registered",
    LOGIN_USER: "user-logged-in",
    UPDATE_PROFILE: "profile-updated",
    DELETE_PROFILE: "profile-deleted",
    PROGRESS_UPDATE: "update-progress",
    GET_SITE_SETTINGS: "site-settings",
    UPDATE_SITE_SETTINGS: "site-settings-updated",
    CREATE_GAME: "game-created",
    CURRENT_USERS: "current-users",
    CURRENT_GAMES: "current-games",
    PLAY_MOVE: "move-played",
    LOAD_GAME: "game-loaded",
    RENAME_GAME: "game-renamed",
    CHANGE_ICON: "icon-changed",
    RESET_ROUNDS: "rounds-reset",
    DELETE_GAME: "game-deleted",
    RECENT_GAMES: "recent-games",
    JOIN_CHATS: "conversations",
    START_CONVERSATION: "conversation-started",
    JOIN_CHAT: "chat-joined",
    SEND_MESSAGE: "message-sent",
  };
}

module.exports = Socket;
